PROJECT_NAME = game
CC = gcc
BIN_DIR = ../bin
SRCS = main.c level.c player.c bot.c projectile.c asset.c pile.c

CFLAGS = -Wall -std=c99 -Wno-missing-braces -I. -I../lib/linux/raylib-5.5_linux_amd64/include
LDFLAGS = -L../lib/linux/raylib-5.5_linux_amd64/lib -lraylib -lGL -lm -lpthread -ldl -lrt -lX11

all: $(BIN_DIR)/$(PROJECT_NAME)

$(BIN_DIR)/$(PROJECT_NAME): $(SRCS)
	mkdir -p $(BIN_DIR)
	$(CC) $^ -o $@ $(CFLAGS) $(LDFLAGS)

run: all
	./$<

clean:
	rm -f $(BIN_DIR)/$(PROJECT_NAME)

info:
	@echo "Platform: LINUX"
	@echo "Raylib:   ../lib/linux/raylib"
	@echo "Binary:   $(BIN_DIR)/$(PROJECT_NAME)"